services:
  mysql_db:
    image: mysql:8.0
    container_name: lider_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lider_refrigeracao
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: lider_phpmyadmin
    restart: always
    depends_on:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  mysql_data:
